package com.example.meshguard.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.meshguard.data.model.ChatMessage
import com.example.meshguard.data.model.DeliveryState
import com.example.meshguard.data.model.MessageType

/**
 * Step 12: Room entity for a single chat message stored in local SQLite.
 * Primary key is [id] — a UUID generated by the sender.
 * Duplicate inserts (gossip relay loops) are silently ignored via IGNORE conflict strategy.
 */
@Entity(tableName = "chat_messages")
data class ChatMessageEntity(
    @PrimaryKey
    val id: String,
    val senderId: String,
    val senderName: String,
    val type: String,            // MessageType.name
    val content: String,
    val audioDurationSec: Int,
    val hopCount: Int,
    val ttl: Int,
    val deliveryState: String,   // DeliveryState.name
    val timestamp: Long,
    val isFromMe: Boolean
) {
    fun toChatMessage(): ChatMessage = ChatMessage(
        id = id,
        senderId = senderId,
        senderName = senderName,
        type = try { MessageType.valueOf(type) } catch (e: Exception) { MessageType.TEXT },
        content = content,
        audioDurationSec = audioDurationSec,
        hopCount = hopCount,
        deliveryState = try { DeliveryState.valueOf(deliveryState) } catch (e: Exception) { DeliveryState.STORED },
        timestamp = timestamp,
        isFromMe = isFromMe
    )

    companion object {
        fun fromChatMessage(msg: ChatMessage, ttl: Int = 8): ChatMessageEntity = ChatMessageEntity(
            id = msg.id,
            senderId = msg.senderId,
            senderName = msg.senderName,
            type = msg.type.name,
            content = msg.content,
            audioDurationSec = msg.audioDurationSec,
            hopCount = msg.hopCount,
            ttl = ttl,
            deliveryState = msg.deliveryState.name,
            timestamp = msg.timestamp,
            isFromMe = msg.isFromMe
        )
    }
}
